pipelineAccount:
  awsAccountId: 288378107057
  awsRegion: ap-northeast-1

devAccount:
  awsAccountId: 288378107057
  awsRegion: ap-northeast-1

prodAccount:
  awsAccountId: 288378107057
  awsRegion: us-east-1

dev:
  jobs:
    deploy-test:
      input_path: "s3://xuao-s3-test2/dev/"
      table_name: "member_dev"

prod:
  jobs:
    deploy-test:
      input_path: "s3://xuao-s3-test2/prod/"
      table_name: "member_pord"