pipelineAccount:
  awsAccountId: 288378107057
  awsRegion: ap-northeast-1

devAccount:
  awsAccountId: 288378107057
  awsRegion: ap-northeast-1

prodAccount:
  awsAccountId: 288378107057
  awsRegion: ap-northeast-1

dev:
  jobs:
    ProcessLegislators:
      inputLocation: s3://awsglue-datasets/examples/us-legislators/all/persons.json

prod:
  jobs:
    ProcessLegislators:
      inputLocation: s3://awsglue-datasets/examples/us-legislators/all/persons.json