pipelineAccount:
  awsAccountId: 288378107057
  awsRegion: ap-northeast-1

devAccount:
  awsAccountId: 288378107057
  awsRegion: ap-northeast-1

stgAccount:
  awsAccountId: 288378107057
  awsRegion: ap-northeast-1

prodAccount:
  awsAccountId: 288378107057
  awsRegion: ap-northeast-1

dev:
  jobs:
    testxuao1:
      inputLocation: s3://awsglue-datasets/dev/persons.json

stg:
  jobs:
    testxuao1:
      inputLocation: s3://awsglue-datasets/stg/persons.json

prod:
  jobs:
    testxuao1:
      inputLocation: s3://awsglue-datasets/prod/persons.json