pipelineAccount:
  awsAccountId: "961341542235"
  awsRegion: "ap-northeast-1"

assets_path: "s3://aws-glue-assets-961341542235-ap-northeast-1"

github:
  repo: "xuao-private/aws-glue-cicd-test"
  branch: "staging"
  connection_arn: "arn:aws:codeconnections:ap-northeast-1:961341542235:connection/78aa1400-8f4b-4aa4-8e0f-4b94b703bc1b"

jobs:
  deploy-test:
    input_path: "s3://xuao-s3-test2/stg/"
    table_name: "member_stg"
    glue_role: "arn:aws:iam::961341542235:role/service-role/AWSGlueServiceRole-stg"