# dev環境設定
pipelineAccount:
  awsAccountId: "961341542235"
  awsRegion: "ap-northeast-1"

# Glueアセット格納用S3バケット
assets_path: "s3://aws-glue-assets-deploy-test-dev"

# GitHub 設定
github:
  repo: "xuao-private/aws-glue-cicd-test"
  branch: "develop"
  connection_arn: "arn:aws:codeconnections:ap-northeast-1:961341542235:connection/78aa1400-8f4b-4aa4-8e0f-4b94b703bc1b"